language: python

python:
  - "3.8"

install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev
    
before_script:
  - cd gtt_ci
    
script:
  - python manage.py test